---
- hosts: postgresql_nodes
  become: yes
  vars:
    postgresql_version: "14"
    patroni_config_dir: "/etc/patroni"
    postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/data"
    pgbouncer_listen_port: 6432
    pgbouncer_listen_addr: "0.0.0.0"
    pgbouncer_auth_type: "md5"
    pgbouncer_pool_mode: "session"
    cluster_name: "pg_cluster"
    node_name: "{{ inventory_hostname }}"
    patroni_etcd_url: "{{ inventory_hostname }}:2379"

  tasks:
    # Конфигурация PgBouncer
    - name: Установка PgBouncer
      apt:
        name: pgbouncer
        state: present

    - name: Настройка PgBouncer
      copy:
        dest: /etc/pgbouncer/pgbouncer.ini
        content: |
          [databases]
          * = host=localhost port=5432

          [pgbouncer]
          listen_addr = {{ pgbouncer_listen_addr }}
          listen_port = {{ pgbouncer_listen_port }}
          auth_type = {{ pgbouncer_auth_type }}
          auth_file = /etc/pgbouncer/userlist.txt
          pool_mode = {{ pgbouncer_pool_mode }}
          max_client_conn = 1000
          default_pool_size = 20

    - name: Добавление пользователей PgBouncer
      copy:
        dest: /etc/pgbouncer/userlist.txt
        content: |
           "postgres" "{{ postgresql_superuser_password }}"
#           "postgres" "md5{{ postgresql_superuser_password | password_hash('md5') }}"

    - name: Configure systemd service for PgBouncer
      copy:
        content: |
          [Unit]
          Description=PgBouncer
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/sbin/pgbouncer /etc/pgbouncer/pgbouncer.ini
          User=postgres
          Group=postgres
          Restart=always

          [Install]
          WantedBy=multi-user.target

        dest: /etc/systemd/system/pgbouncer.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

#    - name: Запуск PgBouncer
#      systemd:
#        name: pgbouncer
#        state: started
#        enabled: yes

    - name: Запуск PgBouncer
      systemd:
        name: pgbouncer
        enabled: yes
        state: restarted
