---
- hosts: postgresql_nodes
  become: yes
  vars:
    postgresql_version: "13"
    postgresql_data_dir: "/var/lib/pgsql/{{ postgresql_version }}/data"
  tasks:
    - name: Install PostgreSQL repository
      yum:
        name: "https://download.postgresql.org/pub/repos/yum/{{ postgresql_version }}/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        state: present

    - name: Install PostgreSQL server and client
      yum:
        name:
          - postgresql{{ postgresql_version }}
          - postgresql{{ postgresql_version }}-server
        state: present

    - name: Initialize PostgreSQL database
      shell: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb"
      args:
        creates: "{{ postgresql_data_dir }}/PG_VERSION"

    - name: Enable and start PostgreSQL service
      systemd:
        name: postgresql-{{ postgresql_version }}
        enabled: yes
        state: started

    - name: Set PostgreSQL password for default user
      postgresql_user:
        user: postgres
        password: "mysecurepassword"
