version: '3.9'

networks:
  kafka-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      kafka-net:
        ipv4_address: 192.168.100.10

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://192.168.100.11:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.100.11:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zookeeper
    networks:
      kafka-net:
        ipv4_address: 192.168.100.11

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://192.168.100.12:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.100.12:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zookeeper
    networks:
      kafka-net:
        ipv4_address: 192.168.100.12

  kafka3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://192.168.100.13:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.100.13:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zookeeper
    networks:
      kafka-net:
        ipv4_address: 192.168.100.13

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 192.168.100.11:9092,192.168.100.12:9093,192.168.100.13:9094
      KAFKA_CLUSTERS_0_ZOOKEEPER: 192.168.100.10:2181
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      kafka-net:
        ipv4_address: 192.168.100.20


  logstash:
    build:
      context: ./logstash  # Путь к папке, где находится Dockerfile
      dockerfile: Dockerfile  # Имя Dockerfile, если оно отличается от стандартного
    container_name: logstash-kafka
    volumes:
      #- ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./pipeline/:/usr/share/logstash/pipeline/:ro
    ports:
      - "5044:5044"  # Beats input
      - "9600:9600"  # Logstash monitoring API
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m

    extra_hosts:
      - "host.docker.internal:host-gateway"
