postgresql_version: "14"
patroni_config_dir: "/etc/patroni"
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/data"
pgbouncer_listen_port: 6432
pgbouncer_listen_addr: "0.0.0.0"
pgbouncer_auth_type: "md5"
pgbouncer_pool_mode: "session"
cluster_name: "pg_cluster"
node_name: "{{ inventory_hostname }}"
patroni_etcd_url: "{{ inventory_hostname }}:2379"
postgresql_superuser_password: "superpass"
replication_password: "replpassword"
etcd_username: "root"
etcd_password: "etcdpassword"

# название базы с которой работаем, пользователь этой базы и пароль
pool_db_name: "mpmpool"
pool_db_user: "mpmpool"
pool_user_pass: "mpmpoolpass"

#etcd_initial_cluster: "node1=http://62.113.106.101:2380,node2=http://31.129.106.65:2380,node3=http://31.128.36.206:2380"
#etcd_cluster: "http://62.113.106.101:2379,http://31.129.106.65:2379,http://31.128.36.206:2379"
