- hosts: etcd
  become: True
  tasks:
    - name: "Create directory for etcdkeeper binaries"
      file:
        path: /opt/etcdkeeper/bin
        state: directory
        owner: root
        group: root
        mode: 0700

    - name: "Download the tarball into the /tmp directory"
      get_url:
        url: https://github.com/evildecay/etcdkeeper/releases/download/v0.7.8/etcdkeeper-v0.7.8-linux_x86_64.tar.gz
        dest: /tmp/etcdkeeper.tar.gz
        owner: root
        group: root
        mode: 0600
        force: True
        validate_certs: no
    - name: "Extract the contents of the tarball"
      unarchive:
        src: /tmp/etcdkeeper.tar.gz
        dest: /opt/etcdkeeper/bin/
#        owner: root
#        group: root
#        mode: 0600
#        extra_opts:
#          - --strip-components=1
        decrypt: True
        remote_src: True

    - name: "Set permissions for etcdkeeper"
      file:
        path: /opt/etcdkeeper/bin/etcdkeeper
        state: file
        owner: root
        group: root
        mode: 0700
    - name: "Add /opt/etcdkeeper/bin/ to the $PATH environment variable"
      lineinfile:
        path: /etc/profile
        line: export PATH="$PATH:/opt/etcdkeeper/bin"
        state: present
        create: True
        insertafter: EOF
    - name: "Create a etcdkeeper service"
      copy:
        src: files/etcdkeeper.service
        remote_src: False
        dest: /etc/systemd/system/etcdkeeper.service
        owner: root
        group: root
        mode: 0644
    - name: "Stop the etcdkeeper service"
      command: systemctl stop etcdkeeper

    - name: "Enable the etcdkeeper service"
      command: systemctl enable etcdkeeper

    - name: "Start the etcdkeeper service"
      command: systemctl restart etcdkeeper



