---
- name: Copy and install .deb package
  hosts: elasticsearch
  become: true
  tasks:
    - name: Copy .deb file to remote server
      copy:
        src: elasticsearch-8.16.1-amd64.deb
        dest: /tmp/elasticsearch.deb
        mode: '0644'

