---
- name: Install and configure Elasticsearch cluster
  hosts: elasticsearch
  become: true

  vars:
    elastic_version: "8.9.2"
    cluster_name: "my_elastic_cluster"
    node_name: "{{ inventory_hostname }}"
    es_data_path: "/var/lib/elasticsearch"
    es_log_path: "/var/log/elasticsearch"
    es_heap_size: "1g"

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - openjdk-11-jdk
          - wget
        state: present
      when: ansible_os_family == "Debian"

    # Установка elastic из пакета. Предварительно скопировать (плейбук copy_elastic.yaml) пакет установки elastic в директорию /tmp
    - name: Install the .deb package
      command:
        cmd: dpkg -i /tmp/elasticsearch.deb


#    - name: Add Elasticsearch GPG key
#      apt_key:
#        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
#        state: present

#    - name: Add Elasticsearch repository
#      apt_repository:
#        repo: "deb https://artifacts.elastic.co/packages/{{ elastic_version }}/apt stable main"
#        state: present

#    - name: Install Elasticsearch
#      apt:
#        name: elasticsearch
#        state: present
#        update_cache: true

    - name: Configure Elasticsearch
      template:
#        src: elasticsearch.yml.j2
        src: single_elastic.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: 0644

#    - name: Configure JVM heap size
#      lineinfile:
#        path: /etc/elasticsearch/jvm.options
#        regexp: '^-X(ms|mx).*'
#        line: "{{ item }}"
#      with_items:
#        - "-Xms{{ es_heap_size }}"
#        - "-Xmx{{ es_heap_size }}"

    - name: Configure JVM heap size
      lineinfile:
        path: /etc/elasticsearch/jvm.options
        regexp: '^-Xms.*'
        line: "{{ item }}"
      with_items:
        - "-Xms{{ es_heap_size }}"

    - name: Configure JVM heap size
      lineinfile:
        path: /etc/elasticsearch/jvm.options
        regexp: '^-Xmx.*'
        line: "{{ item }}"
      with_items:
        - "-Xmx{{ es_heap_size }}"

    - name: Ensure data and log directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: elasticsearch
        group: elasticsearch
        mode: 0755
      with_items:
        - "{{ es_data_path }}"
        - "{{ es_log_path }}"

    - name: Enable and start Elasticsearch
      systemd:
        name: elasticsearch
        enabled: true
        state: started
