version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      #- xpack.license.self_generated.type=basic
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
    networks:
      - efk

  kibana:
#    image: docker.elastic.co/kibana/kibana:8.9.2
    image: custom-kibana
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
    ports:
      - "5601:5601"
    networks:
      - efk
    depends_on:
      - elasticsearch

  fluentd:
    image: fluent/fluentd:v1.16-1
    container_name: fluentd
    build:
      context: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - efk
    depends_on:
      - elasticsearch

networks:
  efk:
    driver: bridge
