version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
#      KAFKA_LISTENER_NAME_INSIDE: INSIDE
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
#      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092

#  connect:
#    image: confluentinc/cp-kafka-connect:latest
#    depends_on:
#      - kafka
#    environment:
#      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
#      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
#      CONNECT_GROUP_ID: "connect-cluster"
#      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
#      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
#      CONNECT_STATUS_STORAGE_TOPIC: "connect-statuses"
#      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
#      CONNECT_REST_PORT: 8083
#      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_ELASTICSEARCH_URL: "http://host.docker.internal:9200"
#      CONNECT_ELASTICSEARCH_INDEX: "pool-alph"
#
#    volumes:
#      - ./plugins:/usr/share/confluent-hub-components

  connect:
    container_name: kafka-connect
    image: confluentinc/cp-kafka-connect:latest
    ports:
      - "8083:8083"
    depends_on:
      - zookeeper
      - kafka
    environment:

      ######
#      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
#      CONNECT_REST_PORT: 8083
#      CONNECT_GROUP_ID: "connect"
#      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
#      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
#      CONNECT_STATUS_STORAGE_TOPIC: connect-statuses
#      CONNECT_REPLICATION_FACTOR: 1
#      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
#      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
#      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
#      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
#      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
#      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181
#      CONNECT_PLUGIN_PATH: /connect-plugins
#      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
#      CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
#      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-3.3.0.jar
      ######

      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_REST_PORT: 8083
#      CONNECT_ELASTICSEARCH_URL: "http://host.docker.internal:9200"
      CONNECT_GROUP_ID: "kafka-connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-statuses"
##      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
##      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECTOR_CLASS: "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector"
      CONNECT_ELASTICSEARCH_INDEX: "pool-alph"
      CONNECT_ELASTICSEARCH_TYPE: "_doc"
      CONNECT_TOPICS: "PoolsLogs"
      CONNECT_TASKS_MAX: 1
##      CONNECT_PLUGIN_PATH: "/usr/share/java"
#      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
#      #CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-3.3.0.jar
#      CLASSPATH: /usr/share/java/*.jar

    volumes:
      - ./plugins:/usr/share/java/

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
