FROM docker.elastic.co/kibana/kibana:8.9.2

# Копируем сертификат в контейнер
#COPY http_ca.crt /tmp/http_ca.crt

# Обновляем конфигурацию Kibana
#RUN echo 'elasticsearch.ssl.certificateAuthorities: /tmp/http_ca.crt' >> /usr/share/kibana/config/kibana.yml
