server:
  http_listen_port: 3100
#  log_level: debug

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4327
        http:
          endpoint: 0.0.0.0:4328
ingester:
#  lifecycler:
#    ring:
#      kvstore:
#        store: inmemory
#      replication_factor: 1

  max_block_duration: 1s         # Минимальная задержка для буферов
  flush_check_period: 1s          # Частая проверка на сброс
  max_block_bytes: 2097152            # Небольшие блоки для быстрой записи (размер в байтах)

compactor:
  compaction:
    compaction_window: 2h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo

#overrides:
#  per_tenant_override_config: /etc/tempo/overrides.yaml
#  max_traces_per_user: 500000
